
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MODELO
{

using System;
    using System.Collections.Generic;
    
public partial class CONVENIO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CONVENIO()
    {

        this.PARTICIPANTE = new HashSet<PARTICIPANTE>();

    }


    public int numConvenio { get; set; }

    public string nombreInstrumento { get; set; }

    public Nullable<System.DateTime> inicioConvenio { get; set; }

    public Nullable<System.DateTime> finConvenio { get; set; }

    public string plazoConvenio { get; set; }

    public bool publicadoActivo { get; set; }

    public string publicadoDonde { get; set; }

    public string objetivoInstrumento { get; set; }

    public int idNaturaleza { get; set; }

    public Nullable<int> naturalezaModalidad { get; set; }

    public string becas { get; set; }

    public Nullable<int> movilidad { get; set; }

    public string prestacionServicio { get; set; }

    public string donacion { get; set; }

    public string comodato { get; set; }

    public string educacionContinua { get; set; }

    public string nombreRepITH { get; set; }

    public string nombreInstitucion { get; set; }

    public string nombreRepInstitucion { get; set; }

    public string cargoRepInstitucion { get; set; }

    public int idRecursos { get; set; }

    public Nullable<double> montoRecursoFinanciero { get; set; }

    public bool propiedadIntelActivo { get; set; }

    public string propiedadIntelDonde { get; set; }

    public string entregable { get; set; }

    public int idTipoConvenio { get; set; }

    public int idTipoConvenioEsp { get; set; }

    public int idSector { get; set; }

    public int idActEcon { get; set; }

    public Nullable<int> cantidadActEcon { get; set; }

    public int idAmbito { get; set; }

    public string eje { get; set; }

    public bool ODSActivo { get; set; }

    public Nullable<int> idODS { get; set; }

    public Nullable<int> num_participantes { get; set; }



    public virtual ACTIVIDADECONOMICA ACTIVIDADECONOMICA { get; set; }

    public virtual AMBITO AMBITO { get; set; }

    public virtual NATURALEZA NATURALEZA { get; set; }

    public virtual ODS ODS { get; set; }

    public virtual RECURSOS RECURSOS { get; set; }

    public virtual SECTOR SECTOR { get; set; }

    public virtual TIPOCONVENIO TIPOCONVENIO { get; set; }

    public virtual TIPOCONVENIOESP TIPOCONVENIOESP { get; set; }

    public virtual MODALIDAD MODALIDAD { get; set; }

    public virtual MODALIDAD MODALIDAD1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PARTICIPANTE> PARTICIPANTE { get; set; }

}

}
