
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MODELO
{

using System;
    using System.Collections.Generic;
    
public partial class PARTICIPANTE_CARRERA
{

    public int idParticipanteCarrera { get; set; }

    public int idTablaParticipante { get; set; }

    public string nombreCarrera { get; set; }

    public string nombreAlumno { get; set; }

    public string numeroControl { get; set; }



    public virtual PARTICIPANTE PARTICIPANTE { get; set; }

}

}
