//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE
    {
        public int idParticipante { get; set; }
        public string nombreParticipante { get; set; }
        public string rol { get; set; }
        public string carrera { get; set; }
        public int idProyecto { get; set; }
    
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
