
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MODELO
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PARTICIPANTE
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PARTICIPANTE()
    {

        this.PARTICIPANTE_CARRERA = new HashSet<PARTICIPANTE_CARRERA>();

    }


    public int idTablaParticipante { get; set; }

    public string nombreProyecto { get; set; }

    public Nullable<int> num_participantes { get; set; }

    public Nullable<int> num_convenio { get; set; }

    public string semestre { get; set; }

    public virtual CONVENIO CONVENIO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]


    public virtual ICollection<PARTICIPANTE_CARRERA> PARTICIPANTE_CARRERA { get; set; }

}

}
