
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MODELO
{

using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD:Sistema_Convenios/MODELO/TablaParticipantes.cs
public partial class TablaParticipantes
{

    public int numConvenio { get; set; }

    public string nombreInstrumento { get; set; }

    public Nullable<System.DateTime> inicioConvenio { get; set; }

    public Nullable<System.DateTime> finConvenio { get; set; }

    public string plazoConvenio { get; set; }

    public string nombreInstitucion { get; set; }

    public int idTablaParticipante { get; set; }

    public string nombreProyecto { get; set; }

    public Nullable<int> num_participantes { get; set; }

    public Nullable<int> num_convenio { get; set; }

    public string semestre { get; set; }

}

=======
    public partial class TablaProyectos
    {
        public int numConvenio { get; set; }
        public string nombreProyecto { get; set; }
        public Nullable<int> numParticipantes { get; set; }
        public string nombreInstrumento { get; set; }
        public string nombreInstitucion { get; set; }
        public string nombreRepInstitucion { get; set; }
        public int idProyecto { get; set; }
    }
>>>>>>> ad8086fae783ad73c7918996565e0c8ef6172098:Sistema_Convenios/MODELO/TablaProyectos.cs
}
