//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaProyectos
    {
        public int numConvenio { get; set; }
        public string nombreProyecto { get; set; }
        public Nullable<int> numParticipantes { get; set; }
        public string nombreInstrumento { get; set; }
        public string nombreInstitucion { get; set; }
        public string nombreRepInstitucion { get; set; }
        public int idProyecto { get; set; }
    }
}
