
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MODELO
{

using System;
    using System.Collections.Generic;
    
public partial class TIPOCONVENIOESP
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPOCONVENIOESP()
    {

        this.CONVENIO = new HashSet<CONVENIO>();

    }


    public int idTipoConvenioEsp { get; set; }

    public string descripcionTCE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CONVENIO> CONVENIO { get; set; }

}

}
