
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MODELO
{

using System;
    using System.Collections.Generic;
    
public partial class USUARIO
{

    public int id_usuario { get; set; }

    public string nombre { get; set; }

    public string primer_apellido { get; set; }

    public string segundo_apellido { get; set; }

    public string email { get; set; }

    public string telefono { get; set; }

    public string contrasena { get; set; }

    public string empresa { get; set; }

    public int tipoUsuario { get; set; }



    public virtual TIPOUSUARIO TIPOUSUARIO1 { get; set; }

}

}
