//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE
    {
        public int idTablaParticipante { get; set; }
        public string nombreProyecto { get; set; }
        public Nullable<int> num_participantes { get; set; }
        public Nullable<int> num_convenio { get; set; }
    
        public virtual CONVENIO CONVENIO { get; set; }
    }
}
